language: python
python:
  - 3.7
install:
  - python --version
  - pip install poetry
  - pip install pycodestyle
  - pip install isort
  - pip install python-json-logger
  - pip install flask
  - cp scripts/* /app/scripts/
  - cp src /app/src
  - cp tests /app/tests
  - cp pyproject.toml /app
script:
    - sh scripts/unittest.sh